M48
; DRILL file {KiCad (6.0.6)} date Fri Jun 16 11:28:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-16T11:28:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4263Y-2.1665
X4.6173Y-2.1665
T2
X4.4145Y-2.0472
X4.6291Y-2.0472
T0
M30
