[env:stm32f103cb]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cb
framework = stm32cube
upload_protocol = stlink
build_flags =
  -DSTM32F103xB

[platformio]
default_envs = stm32f103cb
